// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace CSharpTest
{
	public class ItemTool
	{
		private const String tableName = "items";
		private static ItemTool instance;
		private DbAccess db;
		
		static ItemTool ()
		{
			instance = new ItemTool ();
		}
		
		private ItemTool ()
		{
			db = new DbAccess ("data source=CSharpTest.db");
		}
		
		public static ItemTool getInstance ()
		{
			return instance;
		}
		
		public void CreatTable ()
		{
//			db = new DbAccess ("data source=CSharpTest.db");
			db.OpenDB("data source=CSharpTest.db");
			//创建数据库表，与字段
			db.CreateTableById (tableName, new string[]{"name","price","seller"}, new string[] {
				"text",
				"int",
				"text"
			});
			db.CloseSqlConnection();
		}
		
		public void Add (Item item)
		{
			db.OpenDB("data source=CSharpTest.db");
			//添加数据
			db.InsertIntoSpecific (tableName,new string[]{"name","price","seller"},new string[] {//表名
				"'" + item.Name + "'",
				"'" + item.Price + "'",
				"'" + item.Seller + "'"
			});
			db.CloseSqlConnection();
		}
	}
}

