// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace CSharpTest
{
	public class User
	{
		public String UserName{ set; get; }
		
		public String PassWord{ set; get; }
		
		public User ()
		{
		}
		
		public User (String userName, String passWord)
		{
			this.UserName = userName;
			this.PassWord = passWord;
		}
	}
}

